services:
  - type: web
    name: finance-app
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: finance-db
          property: connectionString
      - key: SECRET_KEY
        sync: false

databases:
  - name: finance-db
    databaseName: finance
    user: finance
