databases:
  - name: stock-trading-db
    plan: free
    databaseName: stocktrading
    user: stocktrading

services:
  - type: web
    name: stock-trading-simulator
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "./start.sh"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: stock-trading-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
